name: models
description: Dart package which manages the models for the app.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  p_logger:
    path: ../p_logger