final List<String> locations = [
  'Aba',
  'Abbotsford',
  'Aberdeenshire',
  'Abu Dhabi',
  'Adelaide',
  'Advocate Harbour',
  'Ago-Iwoya',
  'Airdrie',
  'Ajax',
  'Al Baha',
  'Alachua',
  'Albert Bridge',
  'Albert Lea',
  'Alberton',
  'Albuquerque',
  'Aldergrove',
  'Alexandria',
  'Allison',
  'Alliston',
  'Alouette',
  'Alphington',
  'Altamonte Springs',
  'Amarillo',
  'Ames',
  'Amherst',
  'Ancaster',
  'Anderson',
  'Ankeny',
  'Ann Arbor',
  'Annapolis Royal',
  'Antigonish',
  'Apo',
  'Aptos',
  'Arcadia',
  'Arichat',
  'Arlington',
  'Armadale',
  'Arnes',
  'Arnprior',
  'Arrowwood',
  'Ashburn',
  'Ashland',
  'Astra',
  'Atlanta',
  'Auburn',
  'Auckland',
  'Augusta',
  'Aulac',
  'Aurora',
  'Austin',
  'Avonport',
  'Aylesbury Bucks',
  'Aylesford',
  'Aylmer',
  'Ayrshire',
  'Baddeck',
  'Bahama',
  'Baie D\'Urfe',
  'Bainbridge',
  'Bal Harbour',
  'Ballito',
  'Baltimore',
  'Balwyn',
  'Bancroft',
  'Banff',
  'Bangalore',
  'Bangor',
  'Barcelona',
  'Bardon',
  'Barnesville',
  'Barnet',
  'Barrachois',
  'Barrie',
  'Barriere',
  'Barrington',
  'Barrington Passage',
  'Barton',
  'Bass River',
  'Bath',
  'Bathurst',
  'Battleford',
  'Bay D\'espoir',
  'Bay Duvin',
  'Bay Village',
  'Bayside',
  'Beaconsfield',
  'Bear Cove',
  'Bear River',
  'Bear River East',
  'Beaumont',
  'Beaverbank',
  'Bedford',
  'Beechville',
  'Beirut',
  'Belleville',
  'Bellevue',
  'Bellingham',
  'Belliveau Cove',
  'Belmont',
  'Bemidji',
  'Ben Eoin',
  'Beresford',
  'Berkshire',
  'Berlin',
  'Bermuda',
  'Bern',
  'Berwick',
  'Bethany',
  'Bethesda',
  'Bexley',
  'Bible Hill',
  'Bickerton West',
  'Bieldside',
  'Big Bras D\'or',
  'Binbrook',
  'Birch Grove',
  'Birmingham',
  'Bismark',
  'Black Point',
  'Black River',
  'Black\'s Harbour',
  'Blacket\'s Lake',
  'Blackmans Bay',
  'Blackville',
  'Blaine',
  'Blainville',
  'Blairmore',
  'Blandford',
  'Blenheim',
  'Blind Bay',
  'Blockhouse',
  'Bloomington',
  'Bluefield',
  'Blues Mills',
  'Bluffton',
  'Bolingbrook',
  'Bonavista',
  'Bonshaw',
  'Boston',
  'Boularderie Center',
  'Boularderie East',
  'Bountiful',
  'Boutilier\'s Point',
  'Boutlier\'s Point',
  'Bowen Island',
  'Bowling Green',
  'Bowmanville',
  'Bowsen',
  'Bracebridge',
  'Bradenton',
  'Bradford',
  'Brady',
  'Braeside',
  'Bramalea',
  'Brampton',
  'Brandon',
  'Brantford',
  'Bras D\'Or',
  'Brenton',
  'Breslau',
  'Breton',
  'Briarwood',
  'Bridgeport',
  'Bridgetown',
  'Bridgewater',
  'Brierly Brook',
  'Bright\'s Cove',
  'Brighton',
  'Brisbane',
  'Bristol',
  'Brockville',
  'Bronx',
  'Brookfield',
  'Brookline',
  'Brooklyn',
  'Brookside',
  'Brossard',
  'Bruce Mines',
  'Brunswick',
  'Buffalo',
  'Burgeo',
  'Burin',
  'Burin Bay Arm',
  'Burkeville',
  'Burlington',
  'Burnaby',
  'Bushville',
  'Bussum',
  'Butler',
  'Cairo',
  'Calabogie',
  'Caledonia',
  'Calgary',
  'Camarillo',
  'Cambridge',
  'Cambridge Station',
  'Camden',
  'Campbell',
  'Campbell River',
  'Campbellton',
  'Canmore',
  'Canning',
  'Canso',
  'Cap-Rouge',
  'Cape George',
  'Cape Sable Island',
  'Cape Town',
  'Carbonear',
  'Cardiff',
  'Cardston',
  'Carleton',
  'Carmel',
  'Carrolls Corner',
  'Carthage',
  'Cary',
  'Castlegar',
  'Catalone',
  'Cedar',
  'Celina',
  'Centreville',
  'Cerritos',
  'Chamalieres',
  'Chapel Hill',
  'Charles Town',
  'Charlotte',
  'Charlottesville',
  'Charlottetown',
  'Chateauguay',
  'Chatham',
  'Chattanooga',
  'Cheddar',
  'Chelsea',
  'Chemainus',
  'Chermside',
  'Chester',
  'Chester Basin',
  'Chesterfield',
  'Chestermere',
  'Cheticamp',
  'Chetwynd',
  'Cheverie',
  'Cheyenne',
  'Chicago',
  'Chilliwack',
  'Chislehurst',
  'Christchurch',
  'Church Point',
  'Cincinnati',
  'Clare',
  'Clarenville',
  'Clark\'s Harbour',
  'Clarksville',
  'Clemson',
  'Clermont-Ferrand',
  'Cleveland',
  'Cleveland Heights',
  'Clifton',
  'Clovelly',
  'Clovis',
  'Co. Antrim',
  'Co. Kildare',
  'Co. Londonderry',
  'Coaticook',
  'Cochrane',
  'Cockeysville',
  'Coconut Grove',
  'Codys',
  'Coeur D\'Alene',
  'Coldbrook',
  'Cole Harbour',
  'College Bridge',
  'College Park',
  'Colleyville',
  'Collierville',
  'Collingwood',
  'Colorado Springs',
  'Columbia',
  'Columbiaville',
  'Columbus',
  'Como',
  'Comox',
  'Conception Bay South',
  'Concession',
  'Concord',
  'Conestogo',
  'Conquerall Mills',
  'Cooperstown',
  'Coos Bay',
  'Coquitlam',
  'Coral Gables',
  'Cordele',
  'Cordova',
  'Corner Brook',
  'Cornwall',
  'Cornwallis',
  'Coronado',
  'Corpus Christi',
  'Corrales',
  'Corry',
  'Cos Cob',
  'Cote St. Luc',
  'Courcelette',
  'Courtenay',
  'Courtice',
  'Coverdale',
  'Cow Bay',
  'Cowansville',
  'Coxheath',
  'Cracow',
  'Craigavon',
  'Cranbrook',
  'Cremorne',
  'Creston',
  'Crocker Hill',
  'Crownsville',
  'Croydon',
  'Cumberland',
  'Curtin',
  'Dade City',
  'Dalhousie',
  'Dallas',
  'Danbury',
  'Daniels',
  'Danville',
  'Dartmouth',
  'Dauphin',
  'Dawson',
  'Daysprings',
  'Dayton',
  'Dearborn',
  'Debert',
  'Decatur',
  'Deep River',
  'Deer Lake',
  'Defiance',
  'Delaware',
  'Delhi',
  'Delmar',
  'Delphos',
  'Delta',
  'Denton',
  'Denver',
  'Derby',
  'Des Moines',
  'Detroit',
  'Devon',
  'Dewitt',
  'Dexter',
  'Dhahran',
  'Dieppe',
  'Digby',
  'Diligent River',
  'Dingwall',
  'Doaktown',
  'Doha',
  'Dollard Des Ormeaux',
  'Dominion',
  'Don Mills',
  'Donalsonville',
  'Donkin',
  'Dorchester',
  'Dorset',
  'Douglas',
  'Dover',
  'Dresden',
  'Drumbo',
  'Drummodville',
  'Dryden',
  'Dubai',
  'Duluth',
  'Duncan',
  'Duncan\'s Cove',
  'Dundas',
  'Dunrobin',
  'Durand',
  'Durant',
  'Durham',
  'Durrel',
  'Dyersville',
  'Dyfed',
  'East Amherst',
  'East Bay',
  'East Brisbane',
  'East Chester',
  'East Chezzetcook',
  'East Hampton',
  'East LaHave',
  'East Lawrencetown',
  'East Mountain',
  'East Providence',
  'East River',
  'East Riverside',
  'East York',
  'Eastern Passage',
  'Eastleigh',
  'EastMan',
  'Eden Prairie',
  'Edgewood',
  'Edina',
  'Edinburgh',
  'Edmonton',
  'Edmundston',
  'Effingham',
  'Elderbank',
  'Elizabethtown',
  'Ellenboro',
  'Ellershouse',
  'Ellerslie',
  'Ellicott City',
  'Elliott Lake',
  'Elmsdale',
  'Elora',
  'Enfield',
  'Englehart',
  'Englishtown',
  'Enterprise',
  'Erie',
  'Erin',
  'Escondido',
  'Eskasoni',
  'Esquimault',
  'Essex',
  'Essexville',
  'Etobicoke',
  'Eurika',
  'Evansville',
  'Exeter',
  'Fair Oaks',
  'Fairburn',
  'Fairhaven',
  'Fall River',
  'Falls Church',
  'Falmouth',
  'Fargo',
  'Farmville',
  'Faro',
  'Farrell',
  'Fayetteville',
  'Fergus',
  'Fergusons Cove',
  'Fernie',
  'Ferriday',
  'Findlay',
  'Fitzroy',
  'Fleming Island',
  'Fletchers Lake',
  'Fleurimont',
  'Flin Flon',
  'Flint',
  'Florenceville',
  'Flushing',
  'Fonthill',
  'Fort Erie',
  'Fort Frances',
  'Fort Lauderdale',
  'Fort McMurray',
  'Fort Saskatchewan',
  'Fort Smith',
  'Fort St. John',
  'Fort Wayne',
  'Fort Worth',
  'Fountain Valley',
  'Frankfort',
  'Frederick',
  'Fredericton',
  'Fredonia',
  'Fredricton',
  'Freeport',
  'Fremantle',
  'Fremont',
  'French River',
  'French Road',
  'Fresh Meadows',
  'Fresno',
  'Friendwood',
  'Fullerton',
  'Gabarus',
  'Gadsden',
  'Gainesville',
  'Gananoque',
  'Gander',
  'Gap',
  'Gardiner Mines',
  'Gastonia',
  'Gatineau',
  'Gays River',
  'Georgetown',
  'Germantown',
  'Glace Bay',
  'Glastonbury',
  'Glen Haven',
  'Glen Margaret',
  'Glendale',
  'Glenellyn',
  'Glenhaven',
  'Glenview',
  'Glenwood',
  'Gloucester',
  'Glovertown',
  'Goose Bay',
  'Gore',
  'Goshen',
  'Grand Bank',
  'Grand Barachois',
  'Grand Bay',
  'Grand Bay - Westfield',
  'Grand Falls',
  'Grand Falls-Windsor',
  'Grand Forks',
  'Grand Lake',
  'Grand Mira South',
  'Grand Pre',
  'Grand Rapids',
  'Grand River',
  'Grand-Barachois',
  'Grande Prairie',
  'Grande-Digue',
  'Grantham',
  'Grants Pass',
  'Granville Ferry',
  'Grapevine',
  'Great Village',
  'Greater Lakeburn',
  'Greely',
  'Green Brook',
  'Green\'s Harbour',
  'Greenfield',
  'Greenfield Park',
  'Greenville',
  'Greenwich',
  'Greenwood',
  'Grifton',
  'Grimsby',
  'Groves Point',
  'Guelph',
  'Gulf Breeze',
  'Guyana',
  'Guysborough',
  'Hackett\'s Cove',
  'Hackettstown',
  'Haifa',
  'Haileybury',
  'Halfmoon Bay',
  'Halibut Bay',
  'Halifax',
  'Halls Harbour',
  'Hamburg',
  'Hamden',
  'Hamilton',
  'Hammonds Plains',
  'Hampshire',
  'Hampton',
  'Hanford',
  'Hanna',
  'Hannover',
  'Hanover',
  'Hantsport',
  'Hanwell',
  'Happy Valley',
  'Harare',
  'Hardisty',
  'Hardwoodlands',
  'Harker Heights',
  'Harlingen',
  'Harrietsfield',
  'Harriman',
  'Harris',
  'Harrisburg',
  'Harrisonburg',
  'Harrodsburg',
  'Hartsville',
  'Harvey',
  'Hastings',
  'Hatchet Lake',
  'Hatfield Point',
  'Haverford',
  'Hawalli',
  'Haxtun',
  'Hay River',
  'Hays',
  'Head Chezzetcook',
  'Head of St Margaret\'s Bay',
  'Hebbville',
  'Hebron',
  'Heflin',
  'Heidelberg',
  'Henderson',
  'Henrico',
  'Hermann',
  'Herrin',
  'Herring Cove',
  'Hickory',
  'High River',
  'Highland Beach',
  'Hillsboro',
  'Hillsdale',
  'Holyoke',
  'Homestead',
  'Honolulu',
  'Hopewell',
  'Hopkinsville',
  'Houston',
  'Howie Center',
  'Hubbards',
  'Hubley',
  'Hudson',
  'Hudson Heights',
  'Hummelstown',
  'Hunters Mountain',
  'Huntington Beach',
  'Huntsville',
  'Ile-a-la-Crosse',
  'Ile-Des-Soeurs',
  'Indian Brook',
  'Indianapolis',
  'Ingonish',
  'Inuvik',
  'Inverness',
  'Inverness-Shire',
  'Iowa City',
  'Ipswich',
  'Iqaluit',
  'Iron Mountain',
  'Iroquois',
  'Irvington',
  'Isaacs Harbour',
  'Islamabad',
  'Isle of Man',
  'Isle Of Sky',
  'Italy Cross',
  'Jackson',
  'Jacksonville',
  'Jalisco',
  'James Town',
  'Jeddore',
  'Jenkintown',
  'Johnson City',
  'Johnston',
  'Jonesboro',
  'Jordan Bay',
  'Jordon Falls',
  'Judique',
  'Kabul',
  'Kailua',
  'Kamloops',
  'Kampala',
  'Kanata',
  'Kane',
  'Kansas City',
  'Kao Hsiung Hsien',
  'Kapuskasing',
  'Karachi',
  'Karolinska',
  'Kars',
  'Kazakhstan',
  'Kelowna',
  'Kemble',
  'Kemptville',
  'Kenmore',
  'Kennebunkport',
  'Kennetcook',
  'Kenora',
  'Kenosha',
  'Kensington',
  'Kent',
  'Kentville',
  'Kerala',
  'Kerrobert',
  'Kesrouan',
  'Keswick Ridge',
  'Ketch Harbour',
  'Killam',
  'King City',
  'Kings Head',
  'Kingston',
  'Kingsville',
  'Kinsac',
  'Kinsley',
  'Kippens',
  'Kirkland',
  'Kirkland Lake',
  'Kiryat Motzkin',
  'Kitchener',
  'Knowlton',
  'Knoxville',
  'Kokomo',
  'Kowloon',
  'Kugluktuk',
  'L\'Ardoise',
  'L. De Blanc Sablon',
  'La Prairie',
  'La Ronge',
  'Labrador City',
  'Lac Au Saumon',
  'Lachine',
  'Lacombe',
  'Ladysmith',
  'Lafayette',
  'Lahave',
  'Lahore 54000',
  'Lake Charlotte',
  'Lake City',
  'Lake Echo',
  'Lake Loon',
  'Lake of the Woods',
  'Lakefield',
  'Lakeland',
  'Lakeside',
  'Lakeview',
  'Lakewood',
  'Lancaster',
  'Lancaster Park',
  'Langley',
  'Lansdowne',
  'Lantz',
  'Lantzville',
  'Laredo',
  'Las Vegas',
  'LaSalle',
  'Laterriere',
  'Lauderdale Lakes',
  'Lawrence Town',
  'Lawrenceburg',
  'Lawrencetown',
  'Lazo',
  'Leawood',
  'Lebanon',
  'Leduc',
  'Leesburg',
  'Leichhardt',
  'Leitchfield',
  'Lenexa',
  'Lenoir',
  'Leoti',
  'LePreau',
  'Lery',
  'Lethbridge',
  'Lewis Lake',
  'Lewisporte',
  'Lexington',
  'Liberty',
  'Lima',
  'Limassol',
  'Limehouse',
  'Lincoln',
  'Lincolnville',
  'Lindsay',
  'Little Bras D\'Or',
  'Little Brook',
  'Little Current',
  'Little Falls',
  'Little Narrows',
  'Little Rock',
  'Little Sands',
  'Liverpool',
  'Livingston',
  'Llandudno',
  'Lloydminster',
  'Lockport',
  'Logy Bay',
  'Loma Linda',
  'London',
  'Long Sault',
  'Longueuil',
  'Longview',
  'Longwood',
  'Loogootee',
  'Los Angeles',
  'Louisburg',
  'Louisdale',
  'Louisville',
  'Lowell',
  'Lower Coverdale',
  'Lower Montague',
  'Lower Onslow',
  'Lower Sackville',
  'Lower West Pubnico',
  'Lucasville',
  'Ludlow',
  'Lunenburg',
  'Lusaka',
  'Lutz',
  'Lyle',
  'Lynn',
  'Lyons Brook',
  'Mabou',
  'MacClenny',
  'MacHias',
  'MacKenzie',
  'Madden',
  'Madison',
  'Mahone Bay',
  'Maitland',
  'Malagash',
  'Malden',
  'Malone',
  'Manchester',
  'Manlius',
  'Manotick',
  'Manuels',
  'Maple',
  'Maple Ridge',
  'Marathon',
  'Margaree Centre',
  'Margaree Harbour',
  'Margaree Valley',
  'Marion Bridge',
  'Markdale',
  'Markham',
  'Marshall',
  'Marss Corner',
  'Martinique',
  'Martinsville',
  'Martock',
  'Marysville',
  'Mascouche',
  'Masset',
  'Masson-Angers',
  'Matheson',
  'Maugerville',
  'Mayerthorpe',
  'Mayfield Heights',
  'Maysville',
  'McAllen',
  'McArras Brook',
  'McCaysville',
  'McDonald',
  'McMurray',
  'Meadowvale',
  'Meaford',
  'Medfield',
  'Medicine Hat',
  'Melaka',
  'Melbourne',
  'Melville',
  'Membertou',
  'Memphis',
  'Menands',
  'Mercier',
  'Meridian',
  'Merigomish',
  'Merrickville',
  'Merrimack',
  'Merritt',
  'Metairie',
  'Meteghan',
  'Meteghan Centre',
  'Meteghan River',
  'Miami',
  'Miami Shores',
  'Micmac',
  'Middle Musquodoboit',
  'Middle River',
  'Middle Sackville',
  'Middle West Pubnico',
  'Middlesboro',
  'Middleton',
  'Midhurst',
  'Midland',
  'Midlothian',
  'Milan',
  'Milford Station',
  'Mililani',
  'Mill Bay',
  'Mill Village',
  'Milton',
  'Minden',
  'Mineola',
  'Minesing',
  'Mineville',
  'Minneapolis',
  'Minot',
  'Mira Gut',
  'Mira Road',
  'Miramichi',
  'Mission',
  'Mississauga',
  'Modesto',
  'Monaca',
  'Monahans',
  'Moncton',
  'Monroe',
  'Mont St-Hilaire',
  'Mont-Joli',
  'Montague',
  'Montgomery',
  'Monticello',
  'Montreal',
  'Moose Jaw',
  'Moreno Valley',
  'Morgan Hill',
  'Morganstown',
  'Morristown',
  'Moschelle',
  'Moscow',
  'Mosgiel',
  'Moultrie',
  'Mount Hope',
  'Mount Pearl',
  'Mount Royal',
  'Mount Uniacke',
  'Mount Vernon',
  'Mountain View',
  'Mulgrave',
  'Mulheim',
  'Murfreesboro',
  'Murray Siding',
  'Musquodoboit Harbour',
  'Musquodoboit Valley',
  'Nackawic',
  'Nairobi',
  'Nampally',
  'Nanaimo',
  'Napanee',
  'Naples',
  'Narberth',
  'Nashua',
  'Nashville',
  'Nassau',
  'Natural Dam',
  'Nedlands',
  'Needham',
  'Neils Harbour',
  'Nelson',
  'Nepean',
  'Nevada City',
  'New Albany',
  'New Bedford',
  'New Brunswick',
  'New Delhi',
  'New Edinburgh',
  'New Germany',
  'New Glasgow',
  'New Harbour',
  'New Haven',
  'New Limerick',
  'New Liskeard',
  'New Martinsville',
  'New Maryland',
  'New Minas',
  'New Orleans',
  'New Providence',
  'New Rochelle',
  'New Ross',
  'New Smyrna Beach',
  'New Victoria',
  'New Waterford',
  'New Westminster',
  'New York',
  'Newbridge',
  'Newburgh',
  'Newcastle',
  'Newmarket',
  'Newport',
  'Newton',
  'Newtown',
  'Niagara Falls',
  'Nictaux',
  'Nine Mile River',
  'Niskayuna',
  'Nobleton',
  'Noel',
  'Noel Shore',
  'Norfolk',
  'Normal',
  'North Andover',
  'North Battleford',
  'North Bay',
  'North Bend',
  'North Bethesda',
  'North Chegoggin',
  'North Collins',
  'North Delta',
  'North Falmouth',
  'North Guildford',
  'North Houston',
  'North Lake',
  'North Preston',
  'North Sydney',
  'North Vancouver',
  'North York',
  'Northborough',
  'Northport',
  'Northside East Bay',
  'Norwalk',
  'O\'Leary',
  'Oak Hill',
  'Oak Lawn',
  'Oakfield',
  'Oakland',
  'Oakville',
  'Ocala',
  'Ogdensburg',
  'Old Barns',
  'Old Fort',
  'Oliver',
  'Omemee',
  'Oneonta',
  'Ontario',
  'Open',
  'Orange',
  'Orangeville',
  'Orchard Park',
  'Orford',
  'Orillia',
  'Orleans',
  'Ormstown',
  'Oromocto',
  'Orono',
  'Osborne Corner',
  'Oshawa',
  'Oshikosh',
  'Oslo',
  'Osoyoos',
  'Ossian',
  'Ossining',
  'Ottawa',
  'Ouston',
  'Outer Cover',
  'Outlook',
  'Outremont',
  'Overland Park',
  'Owen Sound',
  'Oxford',
  'Oxford Junction',
  'Oxnard',
  'Oxon',
  'Paducah',
  'Paisley',
  'Palm Desert',
  'Palm Dessert',
  'Palm Springs',
  'Palo Alto',
  'Pampanga',
  'Panama City',
  'Paoli',
  'Papillion',
  'Papua New Guinea',
  'Paradise',
  'Paris',
  'Parksville',
  'Parow',
  'Parrsboro',
  'Parry Sound',
  'Pasadena',
  'Peace River',
  'Pearland',
  'Pemberton',
  'Pembroke',
  'Penicuik',
  'Penn Yan',
  'Penticton',
  'Peoria',
  'Perth',
  'Perth-Andover',
  'Petawawa',
  'Peterborough',
  'Petersburg',
  'Petit de Grat',
  'Petit-Etang',
  'Petite Riviere',
  'Philadelphia',
  'Phoenix',
  'Pickering',
  'Picton',
  'Pictou',
  'Pictou Landing',
  'Pierrefonds',
  'Pikeville',
  'Pinegrove',
  'Pittsburg',
  'Pittsburgh',
  'Pittsford',
  'Placitas',
  'Plainsboro',
  'Plano',
  'Plantation',
  'Plaster Rock',
  'Pleasant Bay',
  'Pleasantville',
  'Point Aconi',
  'Point Edward',
  'Pointe Claire',
  'Pointe du Chene',
  'Pointe-de-l\'Eglise',
  'Pokfulam',
  'Poland',
  'Poltimore',
  'Pompton Lakes',
  'Ponoka',
  'Pont Landry',
  'Port Alberni',
  'Port Angeles',
  'Port Arthur',
  'Port Charlotte',
  'Port Clinton',
  'Port Clyde',
  'Port Colborne',
  'Port Coquitlam',
  'Port George',
  'Port Hardy',
  'Port Hastings',
  'Port Hawkesbury',
  'Port Hood',
  'Port Howe',
  'Port Joli',
  'Port Moody',
  'Port Morien',
  'Port Mouton',
  'Port Of Spain',
  'Port Perry',
  'Port Saunders',
  'Port St. Lucie',
  'Port Vila',
  'Port Washington',
  'Port Williams',
  'Portadown',
  'Porters Lake',
  'Portland',
  'Portsmouth',
  'Portugal Cove',
  'Portuguese Cove',
  'Potomac',
  'Powell River',
  'Prattville',
  'Priestville',
  'Prince Albert',
  'Prince William',
  'Princeton',
  'Prospect Bay',
  'Providence',
  'Pt. Edward',
  'Pubnico',
  'Pugwash',
  'Putnam',
  'Qualicum',
  'Quebec City',
  'Queensland',
  'Quinan',
  'Quispamsis',
  'Ra\'anana',
  'Raleigh',
  'Rancho Mirage',
  'Raymond',
  'Raymondville',
  'Raynardton',
  'Readfield',
  'Reading',
  'Red Deer',
  'Red Lake',
  'Redlands',
  'Redondo Beach',
  'Redwood City',
  'Regina',
  'Renfrewshire',
  'Reserve Mines',
  'Rexdale',
  'Richardson',
  'Richelain',
  'Richland',
  'Richmond',
  'Richmond Heights',
  'Richmond Hill',
  'Ridgeland',
  'River Hebert',
  'River John',
  'River Philip',
  'River Ridge',
  'Riverview',
  'Riyadh',
  'Roberts Creek',
  'Rochester',
  'Rockhampton',
  'Rockingham',
  'Rockville',
  'Rockwood',
  'Rocky River',
  'Rogersville',
  'Rome',
  'Rose Bay',
  'Rosemere',
  'Ross Ferry',
  'Rossland',
  'Rothesay',
  'Roux-Miroir',
  'Rouyn-Noranda',
  'Russell',
  'Russellville',
  'Rutherfordton',
  'S. Pasadena',
  'Saanichton',
  'Sable River',
  'Sackville',
  'Sacramento',
  'Saint John',
  'Saint Paul',
  'Saint-Charles',
  'Salem Township',
  'Salmon Arm',
  'Salmon River',
  'Salt Lake City',
  'Salt Spring Island',
  'Salt Springs',
  'Sambro',
  'Sambro Head',
  'San Antonio',
  'San Carlos',
  'San Diego',
  'San Francisco',
  'San Jose',
  'Sanaa',
  'Sandford',
  'Sandringham',
  'Sandy Cove',
  'Sandy Point',
  'Sanibel',
  'Sarasota',
  'Sardis',
  'Sarnia',
  'Saskatoon',
  'Saulnierville',
  'Sault Ste. Marie',
  'Savannah',
  'Scarborough',
  'Scarsdale',
  'Schumacher',
  'Scotch Village',
  'Scotsburn',
  'Scott City',
  'Scottsdale',
  'Seabright',
  'Seaforth',
  'Seattle',
  'Sebring',
  'Sechelt',
  'Seeley\'s Bay',
  'Selma',
  'Seminole',
  'Seneca',
  'Shag Harbour',
  'Shakopee',
  'Shawnigan Lake',
  'Shearwater',
  'Shediac',
  'Sheet Harbour',
  'Sheffield Mills',
  'Shelburne',
  'Shelby',
  'Shelbyville',
  'Sherbrooke',
  'Sherwood',
  'Sherwood Park',
  'Shilo',
  'Shreveport',
  'Shropshire',
  'Shubenacadie',
  'Sidney',
  'Sillery',
  'Siloam Springs',
  'Silver Spring',
  'Simcoe',
  'Sioux City',
  'Sioux Falls',
  'Sioux Lookout',
  'Slave Lake',
  'Slemon Park',
  'Smithers',
  'Smiths Cove',
  'Smiths Falls',
  'Smiths Parish',
  'Smithtown',
  'Smooth Rock Falls',
  'Snohomish',
  'Soddy Daisy',
  'Solihull',
  'Somers',
  'Somerville',
  'Soquel',
  'Souris',
  'South Alton',
  'South Brookfield',
  'South Burlington',
  'South Devon',
  'South Hadley',
  'South Lancaster',
  'South Ohio',
  'South Pasadena',
  'South Portland',
  'South Surrey',
  'Southbridge',
  'Southlake',
  'Southside Boularderie',
  'Southwest Harbor',
  'Spanish Town',
  'Spiritwood',
  'Springdale',
  'Springfield',
  'Springhill',
  'Spruce Grove',
  'Squamish',
  'St Anne de Kent',
  'St Charles-Borromee',
  'St Clements',
  'St John\'s',
  'St Leonards',
  'St Stephen',
  'St-Charles',
  'St. Albans',
  'St. Albert',
  'St. Andrews',
  'St. Anne Mad',
  'St. Anne\'s',
  'St. Anthony',
  'St. Catharines',
  'St. Clair Beach',
  'St. George',
  'St. Jerome',
  'St. John\'s',
  'St. Lambert',
  'St. Laurbert',
  'St. Laurent',
  'St. Leonards',
  'St. Louis',
  'St. Lucia',
  'St. Margarets Bay',
  'St. Paul',
  'St. Peters',
  'St. Petersburg',
  'St. Phillips',
  'St. Stephen',
  'St. Thomas',
  'Staten Island',
  'Statesville',
  'Station Island',
  'Ste anne de Bellevue',
  'Steady Brook',
  'Stellarton',
  'Stephenville',
  'Sterling',
  'Stewiacke',
  'Stillwater Lake',
  'Stirling',
  'Stittsville',
  'Stockholm',
  'Stoufville',
  'Stratford',
  'Strathmore',
  'Stryn',
  'Stuart',
  'Sturgeon County',
  'Sudbury',
  'Suffolk',
  'Sugarland',
  'Sullivan',
  'Summerland',
  'Summerside',
  'Summerville',
  'Summit',
  'Sun City Center',
  'Sunnybrook',
  'Sunnyvale',
  'Sunrise',
  'Surprise',
  'Surrey',
  'Sussex',
  'Swift Current',
  'Sydney',
  'Sydney Forks',
  'Sydney Mines',
  'Sydney River',
  'Sylacauga',
  'Sylvania',
  'Sylvester',
  'Syracuse',
  'Tallahassee',
  'Tallman',
  'Tampa',
  'Tancook Island',
  'Tantallon',
  'Tasmania',
  'Tatamagouche',
  'Tecumseh',
  'Temple',
  'Tennessee Ridge',
  'Terrace',
  'The Woodlands',
  'Thessaloniki',
  'Thief River Falls',
  'Thompson',
  'Thornhill',
  'Thornton',
  'Thunder Bay',
  'Tifton',
  'Tignish',
  'Timberlea',
  'Timmins',
  'Tiverton',
  'Tobago',
  'Toccoa',
  'Tofino',
  'Togus',
  'Torbay',
  'Toronto',
  'Torrance',
  'Toulous',
  'Tower Road',
  'Tracadie',
  'Tracadie-Sheila',
  'Trail',
  'Trenton',
  'Trepassey',
  'Troy',
  'Truro',
  'Truro Heights',
  'Tucson',
  'Tulsa',
  'Tusket',
  'Twillingate',
  'Unionville',
  'Upper Canard',
  'Upper Clements',
  'Upper Economy',
  'Upper Kennetcook',
  'Upper LaHave',
  'Upper Musquodoboit',
  'Upper Nappan',
  'Upper Rawdon',
  'Upper Sackville',
  'Upper Stewiacke',
  'Upper Tantallon',
  'Uranium City',
  'Valley',
  'Vancouver',
  'Vanderhoof',
  'Vanier',
  'Vaughan',
  'Venice',
  'Verdun',
  'Vernon',
  'Vestal',
  'Victor',
  'Victoria',
  'Vikhroli West',
  'Villanova',
  'Ville Mont-Royal',
  'Virginia Beach',
  'Viroqua',
  'Vita',
  'Vulcan',
  'Waasis',
  'Wabash',
  'Waco',
  'Wagmatcook',
  'Wakeeney',
  'Wakefield',
  'Wallingford',
  'Walton',
  'Warner Robins',
  'Warsaw',
  'Washington',
  'Waterdown',
  'Waterloo',
  'Waterside',
  'Watertown',
  'Waterville',
  'Waverley',
  'Waycobah',
  'Welland',
  'Wellington',
  'Wentworth',
  'Wentzell Lake',
  'West Arichat',
  'West Bay Road',
  'West Bloomfield',
  'West Bolton',
  'West Chezzetcook',
  'West Covina',
  'West Dover',
  'West Hartford',
  'West Moorings',
  'West Pennant',
  'West Porters Lake',
  'West Saint John',
  'West Susex',
  'West Toronto',
  'West Windsor',
  'Westbank',
  'Westborough',
  'Westbury',
  'Westchester',
  'Western Shore',
  'Westerose',
  'Westerville',
  'Westfield',
  'Westin',
  'Westmount',
  'Westray',
  'Westville',
  'Wetaskiwin',
  'Weymouth',
  'Whangarei',
  'Wheat Ridge',
  'Wheeling',
  'Whistler',
  'Whitby',
  'White River',
  'White River Junction',
  'White Rock',
  'White\'s Lake',
  'Whitehorse',
  'Whittier',
  'Whycocomagh',
  'Wichita',
  'Wileville',
  'Wilkes-Barre',
  'Williams Lake',
  'Williamstown',
  'Williamsville',
  'Williamswood',
  'Willoughby Hills',
  'Willowdale',
  'Wilmot',
  'Winchester',
  'Windsor',
  'Windsor Junction',
  'Winfield',
  'Wingham',
  'Winnetka',
  'Winnipeg',
  'Wolfville',
  'Wondunna',
  'Woodbridge',
  'Woodstock',
  'Woodville',
  'Worcester',
  'Worcestershire',
  'Worthington',
  'Wytheball',
  'Yankton',
  'Yarmouth',
  'Yellow Grass',
  'Yellowknife',
  'Youngstown',
  'Ypsilanti',
  'Yuba City',
  'Zephyre Hills',
  'Zionsville'
];
