name: medtalk
description: "Biohack, helping patients reach doctors."
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # bloc
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  # firebase
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4

  # External packages
  equatable: ^2.0.5
  flutter_native_splash: ^2.4.1
  gap: ^3.0.1
  formz: ^0.7.0
  font_awesome_flutter: ^10.7.0
  flutter_launcher_icons: ^0.14.1
  flutter_svg: ^2.0.10+1
  stream_transform: ^2.1.0
  uuid: ^4.5.1
  intl: ^0.19.0
  envied: ^0.5.4+1
  skeletonizer: ^1.4.2
  google_maps_flutter: ^2.9.0
  faker: ^2.2.0

  # encryption
  crypton: ^2.2.1

  # Permission handler
  permission_handler: ^11.3.1

  # Agora
  agora_rtc_engine: ^6.3.2

  # Local packages
  p_logger:
    path: packages/p_logger
  formz_inputs:
    path: packages/formz_inputs
  backend:
    path: packages/backend


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1

flutter:

  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/icons/
    - assets/images/

  fonts:
    - family: inriaSans
      fonts:
        - asset: assets/fonts/InriaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/InriaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/InriaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/InriaSans-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/InriaSans-Light.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/InriaSans-LightItalic.ttf
          style: italic
          weight: 100
