name: authentication
description: Dart package which manages the authentication process for the app.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  google_sign_in: ^6.2.1
  equatable: ^2.0.5
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  meta: ^1.15.0
  p_logger:
    path: ../p_logger