name: agora
description: Dart package which manages the agora meeting and video calls for the app.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  logger: ^2.4.0
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.3.1
  authentication:
    path: ../authentication