name: backend
description: Dart package which manages the backend process for the app.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.6
  get_it: ^8.0.0
  injectable: ^2.5.0
  cloud_firestore: ^5.4.4
  crypton: ^2.2.1
  pointycastle: ^3.9.1
  flutter_secure_storage: ^9.2.2
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  async: 2.11.0
  p_logger:
    path: ../p_logger
  shared_preferences: ^2.3.2

dev_dependencies:
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13