name: firebase
description: Dart package which manages the firbase process for the app.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  get_it: ^8.0.0
  injectable: ^2.5.0
  cloud_firestore: ^5.4.4
  equatable: ^2.0.5
  p_logger:
    path: ../p_logger
  models:
    path: ../models
  shared_preferences: ^2.3.2

dev_dependencies:
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13